version: "3.0"
services:
  dashboard:
    build: ./dashboard
    command: npm start
    ports: 
      - "3000:3000"
    restart: on-failure
  about:
    build: ./about
    command: node .
    ports: 
      - "8080:8080"
    restart: on-failure
